# Generated by Django 3.2.8 on 2021-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AlterField(
            model_name='phone',
            name='link',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
