# Generated by Django 3.2.8 on 2021-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20211031_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
