# Generated by Django 3.2.8 on 2021-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='phone',
            name='link',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
