# Generated by Django 3.2.8 on 2021-11-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20211102_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='location',
            field=models.TextField(max_length=200),
        ),
    ]
