# Generated by Django 3.2.8 on 2021-11-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_phone_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phone',
            name='link',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='location',
            field=models.TextField(max_length=500),
        ),
    ]
