# Generated by Django 3.2.8 on 2021-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20211103_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phone',
            name='location',
            field=models.TextField(max_length=200),
        ),
    ]
